---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU pipeline using CodePipeline and CodeBuild for continuous delivery
Parameters:
  Namespace:
    Type: String
    Description: Namespace for stack prefixes
  ServiceName:
    Type: String
    Description: Name of service used for resource namespace
  SourceProvider:
    Type: String
    Description: Provider for source repo
    Default: "GitHub"
    AllowedValues:
    - GitHub
    - CodeCommit
    - S3
  SourceRepo:
    Type: String
    Description: Provider specific repository
    Default: ""
  SourceBranch:
    Type: String
    Description: Source Branch
    Default: "master"
  SourceBucket:
    Type: String
    Description: Source Bucket
    Default: ""
  SourceObjectKey:
    Type: String
    Description: Source Object Key
    Default: ""
  GitHubToken:
    NoEcho: true
    Type: String
    Default: ""
    Description: Secret. It might look something like 9b189a1654643522561f7b3ebd44a1531a4287af OAuthToken with access to Repo. Go to https://github.com/settings/tokens
  BuildType:
    Type: String
    Default: "LINUX_CONTAINER"
    Description: The build container type to use for building the app
  BuildComputeType:
    Type: String
    Default: "BUILD_GENERAL1_SMALL"
    Description: The build compute type to use for building the app
  BuildImage:
    Type: String
    Default: "aws/codebuild/ubuntu-base:14.04"
    Description: The build image to use for building the app
  TestType:
    Type: String
    Default: "LINUX_CONTAINER"
    Description: The build container type to use for testing the app
  TestComputeType:
    Type: String
    Default: "BUILD_GENERAL1_SMALL"
    Description: The build compute type to use for testing the app
  TestImage:
    Type: String
    Default: "aws/codebuild/ubuntu-base:14.04"
    Description: The build image to use for testing the app
  MuType:
    Type: String
    Default: "LINUX_CONTAINER"
    Description: The build container type to use for mu commands
  MuComputeType:
    Type: String
    Default: "BUILD_GENERAL1_SMALL"
    Description: The build compute type to use for mu commands
  MuImage:
    Type: String
    Default: "aws/codebuild/docker:1.12.1"
    Description: The build image to use for mu commands
  MuDownloadBaseurl:
    Type: String
    Default: "https://github.com/stelligent/mu/releases/download"
    Description: The base url to install mu from
  MuDownloadVersion:
    Type: String
    Description: The version of mu to install in CodeBuild
  MuDownloadFile:
    Type: String
    Default: "mu-linux-amd64"
    Description: The name of the mu file to download to install
  DefaultBuildspec:
    Type: String
    Description: The default buildspec to use
  MuFile:
    Type: String
    Description: Path to mu.yml, relative to GitHubRepo
    Default: "mu.yml"
  AcptEnv:
    Type: String
    Description: Name of mu environment to deploy to for testing
    Default: "acceptance"
  ProdEnv:
    Type: String
    Description: Name of mu environment to deploy to for production
    Default: "production"
  EnableBuildStage:
    Type: String
    Description: Enable build stage
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  EnableAcptStage:
    Type: String
    Description: Enable acceptance stage
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  EnableProdStage:
    Type: String
    Description: Enable prod stage
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  CodePipelineRoleArn:
    Type: String
    Description: IAM Role for CodePipeline
  CodeBuildCIRoleArn:
    Type: String
    Description: IAM Role for CodeBuild CI actions
    Default: ""
  CodeBuildCDAcptRoleArn:
    Type: String
    Description: IAM Role for CodeBuild CD actions in ACPT
    Default: ""
  CodeBuildCDProdRoleArn:
    Type: String
    Description: IAM Role for CodeBuild CD actions in PROD
    Default: ""
  MuAcptRoleArn:
    Type: String
    Description: IAM Role for Acpt Stage - used for cross account access
    Default: ""
  MuProdRoleArn:
    Type: String
    Description: IAM Role for Prod Stage - used for cross account access
    Default: ""
Conditions:
  IsS3:
    "Fn::Equals":
      - !Ref SourceProvider
      - 'S3'
  IsCodeCommit:
    "Fn::Equals":
      - !Ref SourceProvider
      - 'CodeCommit'
  IsGitHub:
    "Fn::Equals":
      - !Ref SourceProvider
      - 'GitHub'
  HasSourceRepo:
    "Fn::Not":
      - "Fn::Equals":
        - ""
        - !Ref SourceRepo
  HasSourceBucket:
    "Fn::Not":
      - "Fn::Equals":
        - ""
        - !Ref SourceBucket
  HasSourceObjectKey:
    "Fn::Not":
      - "Fn::Equals":
        - ""
        - !Ref SourceObjectKey
  HasGitHubToken:
    "Fn::Not":
      - "Fn::Equals":
        - ""
        - !Ref GitHubToken
  IsBuildEnabled:
    "Fn::Equals":
      - !Ref EnableBuildStage
      - 'true'
  IsAcptEnabled:
    "Fn::Equals":
      - !Ref EnableAcptStage
      - 'true'
  IsProdEnabled:
    "Fn::Equals":
      - !Ref EnableProdStage
      - 'true'
Resources:
  CodeBuildArtifact:
    Type: AWS::CodeBuild::Project
    Condition: IsBuildEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-artifact
      Description: Build artifact from source
      ServiceRole: !Ref CodeBuildCIRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref BuildType
        ComputeType: !Ref BuildComputeType
        Image: !Sub ${BuildImage}
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30
  CodeBuildImage:
    Type: AWS::CodeBuild::Project
    Condition: IsBuildEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-image
      Description: Build image from artifact
      ServiceRole: !Ref CodeBuildCIRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref MuType
        ComputeType: !Ref MuComputeType
        Image: !Sub ${MuImage}
        EnvironmentVariables:
         - Name: DOCKER_API_VERSION
           Value: 1.24
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          phases:
            build:
              commands:
                - curl -sL ${MuDownloadBaseurl}/v${MuDownloadVersion}/${MuDownloadFile} -o /usr/bin/mu
                - chmod +rx /usr/bin/mu
                - mu -c ${MuFile} svc push
          artifacts:
            files:
              - ${MuFile}
      TimeoutInMinutes: 30
  DeployAcceptance:
    Type: AWS::CodeBuild::Project
    Condition: IsAcptEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-deploy-acceptance
      Description: Deploy image to test environment
      ServiceRole: !Ref CodeBuildCDAcptRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref MuType
        ComputeType: !Ref MuComputeType
        Image: !Sub ${MuImage}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
              DEFAULT_BUILDSPEC: "${DefaultBuildspec}"
          phases:
            build:
              commands:
                - curl -sL ${MuDownloadBaseurl}/v${MuDownloadVersion}/${MuDownloadFile} -o /usr/bin/mu
                - chmod +rx /usr/bin/mu
                - mu -c ${MuFile} --assume-role ${MuAcptRoleArn} --disable-iam env up ${AcptEnv} || echo "Skipping update of environment"
                - mu -c ${MuFile} --assume-role ${MuAcptRoleArn} --disable-iam db up ${AcptEnv} || echo "Skipping update of database"
                - mu -c ${MuFile} --assume-role ${MuAcptRoleArn} --disable-iam svc deploy ${AcptEnv}
                - mu --assume-role ${MuAcptRoleArn} env show ${AcptEnv} -f json > env.json
                - mv buildspec-test.yml buildspec.yml || echo "$DEFAULT_BUILDSPEC" > buildspec.yml
          artifacts:
            files:
              - '**/*'
      TimeoutInMinutes: 30
  TestAcceptance:
    Type: AWS::CodeBuild::Project
    Condition: IsAcptEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-test-acceptance
      Description: Test in the acceptance environment
      ServiceRole: !Ref CodeBuildCIRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref TestType
        ComputeType: !Ref TestComputeType
        Image: !Sub ${TestImage}
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30
  DeployProduction:
    Type: AWS::CodeBuild::Project
    Condition: IsProdEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-deploy-production
      Description: Deploy image to prod environment
      ServiceRole: !Ref CodeBuildCDProdRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref MuType
        ComputeType: !Ref MuComputeType
        Image: !Sub ${MuImage}
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Sub |
          version: 0.2
          env:
            variables:
              DEFAULT_BUILDSPEC: "${DefaultBuildspec}"
          phases:
            build:
              commands:
                - curl -sL ${MuDownloadBaseurl}/v${MuDownloadVersion}/${MuDownloadFile} -o /usr/bin/mu
                - chmod +rx /usr/bin/mu
                - mu -c ${MuFile} --assume-role ${MuProdRoleArn} --disable-iam env up ${ProdEnv} || echo "Skipping update of environment"
                - mu -c ${MuFile} --assume-role ${MuProdRoleArn} --disable-iam db up ${ProdEnv} || echo "Skipping update of database"
                - mu -c ${MuFile} --assume-role ${MuProdRoleArn} --disable-iam svc deploy ${ProdEnv}
                - mu --assume-role ${MuProdRoleArn} env show ${ProdEnv} -f json > env.json
                - mv buildspec-prod.yml buildspec.yml || echo "$DEFAULT_BUILDSPEC" > buildspec.yml
          artifacts:
            files:
              - '**/*'
      TimeoutInMinutes: 30
  TestProduction:
    Type: AWS::CodeBuild::Project
    Condition: IsProdEnabled
    Properties:
      Name: !Sub ${Namespace}-pipeline-${ServiceName}-test-production
      Description: Test in the production environment
      ServiceRole: !Ref CodeBuildCIRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: !Ref TestType
        ComputeType: !Ref TestComputeType
        Image: !Sub ${TestImage}
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !Ref CodePipelineRoleArn
      Name: !Sub ${Namespace}-${ServiceName}
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          InputArtifacts: []
          OutputArtifacts:
          - Name: SourceOutput
          ActionTypeId:
            Fn::If:
            - IsS3
            - Category: Source
              Owner: AWS
              Version: '1'
              Provider: S3
            -
              Fn::If:
              - IsGitHub
              - Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              - Category: Source
                Owner: AWS
                Version: '1'
                Provider: CodeCommit
          Configuration:
            Fn::If:
            - IsS3
            - S3Bucket: 
                Fn::If:
                - HasSourceBucket
                - !Ref SourceBucket
                - !Ref AWS::NoValue
              S3ObjectKey:
                Fn::If:
                - HasSourceObjectKey
                - !Ref SourceObjectKey
                - !Ref AWS::NoValue
            -
              Fn::If:
              - IsGitHub
              - Owner: 
                  Fn::If:
                  - HasSourceRepo
                  - {"Fn::Select": ["0", {"Fn::Split":["/", {"Ref": "SourceRepo"}]}]}
                  - !Ref AWS::NoValue
                Repo:
                  Fn::If:
                  - HasSourceRepo
                  - {"Fn::Select": ["1", {"Fn::Split":["/", {"Ref": "SourceRepo"}]}]}
                  - !Ref AWS::NoValue
                Branch: !Ref SourceBranch
                OAuthToken:
                  Fn::If:
                    - HasGitHubToken
                    - !Ref GitHubToken
                    - !Ref AWS::NoValue
              - RepositoryName:
                  Fn::If:
                  - HasSourceBucket
                  - !Ref SourceRepo
                  - !Ref AWS::NoValue
                BranchName: !Ref SourceBranch
          RunOrder: 1
      - Fn::If:
        - IsBuildEnabled
        - Name: Build
          Actions:
          - Name: Artifact
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: SourceOutput
            OutputArtifacts:
            - Name: ArtifactOutput
            Configuration:
              ProjectName: !Ref CodeBuildArtifact
            RunOrder: 1
          - Name: Image
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: ArtifactOutput
            OutputArtifacts:
            - Name: ImageOutput
            Configuration:
              ProjectName: !Ref CodeBuildImage
            RunOrder: 2
        - !Ref AWS::NoValue
      - Fn::If:
        - IsAcptEnabled
        - Name: Acceptance
          Actions:
          - Name: Deploy
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: SourceOutput
            OutputArtifacts:
            - Name: DeployAcceptanceOutput
            Configuration:
              ProjectName: !Ref DeployAcceptance
            RunOrder: 1
          - Name: Test
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: DeployAcceptanceOutput
            OutputArtifacts:
            - Name: TestAcceptanceOutput
            Configuration:
              ProjectName: !Ref TestAcceptance
            RunOrder: 2
        - !Ref AWS::NoValue
      - Fn::If:
        - IsProdEnabled
        - Name: Production
          Actions:
          - Name: Approve
            ActionTypeId:
              Category: Approval
              Owner: AWS
              Version: '1'
              Provider: Manual
            Configuration:
              CustomData: Approve deployment to production
            RunOrder: 1
          - Name: Deploy
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: SourceOutput
            OutputArtifacts:
            - Name: DeployProductionOutput
            Configuration:
              ProjectName: !Ref DeployProduction
            RunOrder: 2
          - Name: Test
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
            - Name: DeployProductionOutput
            OutputArtifacts:
            - Name: TestProductionOutput
            Configuration:
              ProjectName: !Ref TestProduction
            RunOrder: 3
        - !Ref AWS::NoValue
      ArtifactStore:
        Type: S3
        Location:
          Fn::ImportValue: !Sub ${Namespace}-bucket-codepipeline
Outputs:
  CodePipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
    Description: CodePipeline URL
  PipelineName:
    Value: !Sub ${Pipeline}
    Description: Pipeline Name
