---
AWSTemplateFormatVersion: '2010-09-09'
Description: MU IAM roles and keys for a service
Parameters:
  Namespace:
    Type: String
    Description: Namespace for stack prefixes
  EnvironmentName:
    Type: String
    Description: Name of environment used for resource namespace
  ServiceName:
    Type: String
    Description: Name of service used for resource namespace
  Provider:
    Type: String
    Description: Provider type for services
    Default: "ecs"
    AllowedValues:
      - "ecs"
      - "ecs-fargate"
      - "ec2"
      - "eks"
      - "eks-fargate"
      - "batch"
  CodeDeployBucket:
    Type: String
    Description: Name of bucket to use for the CodeDeployBucket artifacts
  DatabaseName:
    Type: String
    Description: Name of database
    Default: ""
Conditions:
  IsEc2Service:
    "Fn::Equals":
      - !Ref Provider
      - 'ec2'
  IsEcsService:
    "Fn::Or":
      - "Fn::Equals":
        - !Ref Provider
        - 'ecs'
      - "Fn::Equals":
        - !Ref Provider
        - 'ecs-fargate'
  IsEksService:
    "Fn::Or":
      - "Fn::Equals":
        - !Ref Provider
        - 'eks'
      - "Fn::Equals":
        - !Ref Provider
        - 'eks-fargate'
  IsBatchService:
    "Fn::Equals":
      - !Ref Provider
      - 'batch'
  HasDatabase:
    "Fn::Not":
      - "Fn::Equals":
        - !Ref DatabaseName
        - ''
Resources:
  DatabaseKey:
    Condition: HasDatabase
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub Service key for ${Namespace}-service-${ServiceName}-${EnvironmentName}
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
              - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - 'kms:*'
            Resource: '*'
          - Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${Namespace}-cloudformation-common-${AWS::Region}
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
              - kms:DescribeKey
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:Encrypt
              - kms:ReEncrypt
              - kms:Decrypt
            Resource: '*'
          - Effect: "Allow"
            Principal:
              AWS: '*'
            Action:
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:Encrypt
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:Decrypt
            Resource: '*'
            Condition:
              StringEquals:
                'kms:ViaService': !Sub "ssm.${AWS::Region}.amazonaws.com"
                'kms:CallerAccount': !Sub ${AWS::AccountId}
          - Effect: "Allow"
            Principal:
              AWS:
              - Fn::If:
                - IsEc2Service
                - !GetAtt EC2Role.Arn
                - !Ref AWS::NoValue
              - Fn::If:
                - IsEcsService
                - !GetAtt EcsTaskRole.Arn
                - !Ref AWS::NoValue
              - Fn::If:
                - IsEksService
                - !GetAtt EksPodRole.Arn
                - !Ref AWS::NoValue
              - Fn::If:
                - IsBatchService
                - !GetAtt BatchTaskRole.Arn
                - !Ref AWS::NoValue
            Action:
              - kms:GenerateDataKey
              - kms:GenerateDataKeyWithoutPlaintext
              - kms:Encrypt
              - kms:ReEncryptFrom
              - kms:ReEncryptTo
              - kms:Decrypt
            Resource: '*'
          - Effect: "Deny"
            Principal: '*'
            Action:
              - 'kms:CreateGrant'
              - 'kms:ListGrants'
              - 'kms:RevokeGrant'
            Resource: '*'
            Condition:
              Bool:
                kms:GrantIsForAWSResource: false
  DatabaseKeyAlias:
    Condition: HasDatabase
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${Namespace}-service-${ServiceName}-${EnvironmentName}
      TargetKeyId: !Ref DatabaseKey
  CodeDeployRole:
    Type: AWS::IAM::Role
    Condition: IsEc2Service
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-codedeploy-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - !Sub codedeploy.${AWS::Region}.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSCodeDeployRole

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Condition: IsEc2Service
    Properties:
      Path: "/"
      Roles:
      - !Ref EC2Role
  EC2Role:
    Type: AWS::IAM::Role
    Condition: IsEc2Service
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-instance-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - !Sub  arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ReadOnlyAccess
      Policies:
      - PolicyName: service-access
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ec2:DescribeTags
            Resource: "*"
          - Effect: Allow
            Action:
            - s3:GetBucketAcl
            - s3:GetBucketLocation
            - s3:GetBucketPolicy
            - s3:GetBucketTagging
            - s3:GetBucketVersioning
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:GetObjectVersion
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:ListBucketVersions
            - s3:ListMultipartUploadParts
            Resource:
            - Fn::Sub: arn:${AWS::Partition}:s3:::${CodeDeployBucket}
            - Fn::Sub: arn:${AWS::Partition}:s3:::${CodeDeployBucket}/*
          - Effect: Allow
            Action:
            - cloudformation:DescribeStackEvents
            - cloudformation:DescribeStackResource
            - cloudformation:DescribeStackResources
            - cloudformation:GetTemplate
            Resource:
            - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${Namespace}-service-${ServiceName}-${EnvironmentName}
            - !Sub arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${Namespace}-service-${ServiceName}-${EnvironmentName}/*
          - Action:
            - cloudformation:DescribeStacks
            Resource: '*'
            Effect: Allow
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogStreams
            - logs:DescribeLogGroups
            Resource: '*'
          - Effect: Allow
            Action:
            - ssm:DescribeAssociation
            - ssm:GetDocument
            - ssm:GetManifest
            - ssm:ListAssociations
            - ssm:ListInstanceAssociations
            - ssm:PutInventory
            - ssm:PutComplianceItems
            - ssm:PutConfigurePackageResult
            - ssm:UpdateAssociationStatus
            - ssm:UpdateInstanceAssociationStatus
            - ssm:UpdateInstanceInformation
            Resource: "*"
          - Effect: Allow
            Action:
            - ssmmessages:CreateControlChannel
            - ssmmessages:CreateDataChannel
            - ssmmessages:OpenControlChannel
            - ssmmessages:OpenDataChannel
            Resource: "*"
          - Effect: Allow
            Action:
            - ec2messages:AcknowledgeMessage
            - ec2messages:DeleteMessage
            - ec2messages:FailMessage
            - ec2messages:GetEndpoint
            - ec2messages:GetMessages
            - ec2messages:SendReply
            Resource: "*"

  ApplicationAutoScalingRole:
    Type: AWS::IAM::Role
    Condition: IsEcsService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-autoscaling-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - application-autoscaling.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
       - PolicyName: autoscale-ecs-service
         PolicyDocument:
           Statement:
           - Effect: Allow
             Action:
             - ecs:UpdateService
             - ecs:DescribeServices
             - cloudwatch:DescribeAlarms
             - cloudwatch:GetMetricStatistics
             - cloudwatch:PutMetricAlarm
             Resource: "*"
  EcsEventsRole:
    Type: AWS::IAM::Role
    Condition: IsEcsService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-events-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - events.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ecs-task
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecs:RunTask
            Resource: "*"
            Condition:
              ArnEquals:
                "ecs:cluster": !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${Namespace}-environment-${EnvironmentName}
          - Effect: Allow
            Action: 
            - iam:PassRole 
            Resource: !GetAtt EcsTaskRole.Arn
            Condition:
              StringLike: 
                "iam:PassedToService": ecs-tasks.amazonaws.com
                
  EcsServiceRole:
    Type: AWS::IAM::Role
    Condition: IsEcsService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-service-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonEC2ContainerServiceRole

  EcsTaskRole:
    Type: AWS::IAM::Role
    Condition: IsEcsService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-task-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ecs-task
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecs:DescribeTasks
            Resource: "*"
            Condition:
              ArnEquals:
                "ecs:cluster": !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${Namespace}-environment-${EnvironmentName}
      - PolicyName: task-execution
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Resource: '*'

  EksPodRole:
    Type: AWS::IAM::Role
    Condition: IsEksService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-pod-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - eks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: pod-execution
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Resource: '*'
            
  BatchTaskRole:
    Type: AWS::IAM::Role
    Condition: IsBatchService
    Properties:
      RoleName: !Sub ${Namespace}-service-${ServiceName}-${EnvironmentName}-batchjob-${AWS::Region}
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: ecs-task
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecs:DescribeTasks
            Resource: "*"
            Condition:
              ArnEquals:
                "ecs:cluster": !Sub arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${Namespace}-environment-${EnvironmentName}
      - PolicyName: task-execution
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            Resource: '*'

Outputs:
  DatabaseKeyArn:
    Description: KMS key for RDS Databases
    Value: 
      Fn::If:
      - HasDatabase
      - !GetAtt DatabaseKey.Arn
      - ''
  EC2InstanceProfileArn:
    Description: Instance profile for EC2 instances
    Value:
      Fn::If:
      - IsEc2Service
      - !GetAtt EC2InstanceProfile.Arn
      - ''
  CodeDeployRoleArn:
    Description: Role assummed by CodeDeploy
    Value:
      Fn::If:
      - IsEc2Service
      - !GetAtt CodeDeployRole.Arn
      - ''
  EcsEventsRoleArn:
    Description: Role assummed by CloudWatch events
    Value:
      Fn::If:
      - IsEcsService
      - !GetAtt EcsEventsRole.Arn
      - ''
  EcsServiceRoleArn:
    Description: Role assummed by ECS Service
    Value:
      Fn::If:
      - IsEcsService
      - !GetAtt EcsServiceRole.Arn
      - ''
  EcsTaskRoleArn:
    Description: Role assummed by ECS Task
    Value:
      Fn::If:
      - IsEcsService
      - !GetAtt EcsTaskRole.Arn
      - ''
  ApplicationAutoScalingRoleArn:
    Description: Role assummed by application autoscaling
    Value:
      Fn::If:
      - IsEcsService
      - !GetAtt ApplicationAutoScalingRole.Arn
      - ''
  BatchJobRoleArn:
    Description: Role assummed by AWS Batch job container
    Value:
      Fn::If:
      - IsBatchService
      - !GetAtt BatchTaskRole.Arn
      - ''