package aws

import (
	// imports to init protobuf registry
	_ "k8s.io/api/apps/v1beta1"
	_ "k8s.io/api/apps/v1beta2"
	/*
		_ "github.com/ericchiang/k8s/apis/admission/v1beta1"
		_ "github.com/ericchiang/k8s/apis/admissionregistration/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/admissionregistration/v1beta1"
		_ "github.com/ericchiang/k8s/apis/apiextensions/v1beta1"
		_ "github.com/ericchiang/k8s/apis/apiregistration/v1"
		_ "github.com/ericchiang/k8s/apis/apiregistration/v1beta1"
		_ "github.com/ericchiang/k8s/apis/apps/v1"
		_ "github.com/ericchiang/k8s/apis/apps/v1beta1"
		_ "github.com/ericchiang/k8s/apis/apps/v1beta2"
		_ "github.com/ericchiang/k8s/apis/authentication/v1"
		_ "github.com/ericchiang/k8s/apis/authentication/v1beta1"
		_ "github.com/ericchiang/k8s/apis/authorization/v1"
		_ "github.com/ericchiang/k8s/apis/authorization/v1beta1"
		_ "github.com/ericchiang/k8s/apis/autoscaling/v1"
		_ "github.com/ericchiang/k8s/apis/autoscaling/v2beta1"
		_ "github.com/ericchiang/k8s/apis/batch/v1"
		_ "github.com/ericchiang/k8s/apis/batch/v1beta1"
		_ "github.com/ericchiang/k8s/apis/batch/v2alpha1"
		_ "github.com/ericchiang/k8s/apis/certificates/v1beta1"
		_ "github.com/ericchiang/k8s/apis/core/v1"
		_ "github.com/ericchiang/k8s/apis/events/v1beta1"
		_ "github.com/ericchiang/k8s/apis/extensions/v1beta1"
		_ "github.com/ericchiang/k8s/apis/imagepolicy/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/meta/v1"
		_ "github.com/ericchiang/k8s/apis/meta/v1beta1"
		_ "github.com/ericchiang/k8s/apis/networking/v1"
		_ "github.com/ericchiang/k8s/apis/policy/v1beta1"
		_ "github.com/ericchiang/k8s/apis/rbac/v1"
		_ "github.com/ericchiang/k8s/apis/rbac/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/rbac/v1beta1"
		_ "github.com/ericchiang/k8s/apis/resource"
		_ "github.com/ericchiang/k8s/apis/scheduling/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/settings/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/storage/v1"
		_ "github.com/ericchiang/k8s/apis/storage/v1alpha1"
		_ "github.com/ericchiang/k8s/apis/storage/v1beta1"
	*/)
